name: Django Docker Compose Deploy

on:
  push:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/django-app
  DOCKER_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          docker-compose up
