name: Django Docker Compose Deploy

on:
  push:

jobs:
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with Docker Compose
        run: |
          cd /home/froggy/backend  # Путь к проекту на сервере
          docker-compose down
          git pull origin master
          docker-compose up -d --build
          docker system prune -f
