name: test workflow

on:
  push:

jobs:
  check-changes:
    runs-on: self-hosted
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend: |
              added: 'frontend/**'
              modified: 'frontend/**'
              deleted: 'frontend/**'
            backend: |
              added: 'backend/**'
              modified: 'backend/**'
              deleted: 'backend/**'

  frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend == 'true'
    runs-on: self-hosted
    steps:
      - run: echo "Building frontend..."

  backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend == 'true'
    runs-on: self-hosted
    steps:
      - run: echo "Building backend..."